# Generated by Django 6.0.5 on 2026-05-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='nome',
            new_name='name',
        ),
    ]
