# Generated by Django 6.0.5 on 2026-05-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_rename_nome_tournament_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='tournameent',
            new_name='tournament',
        ),
    ]
