# Generated by Django 6.0.5 on 2026-05-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_rename_tournameent_team_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('LEAGUE', 'Round Robin League'), ('KNOCKOUT', 'Single Elimination Knockout'), ('GROUP_KNOCKOUT', 'Group Stage + Knockout')], default='LEAGUE', max_length=50),
        ),
    ]
