# Generated by Django 6.0.5 on 2026-05-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_tournament_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('LEAGUE', 'League'), ('KNOCKOUT', 'Knockout'), ('GROUP_KNOCKOUT', 'Group Stage + Knockout')], default='LEAGUE', max_length=50),
        ),
    ]
